name: Build, validate and deploy to staging
on: [pull_request, workflow_dispatch]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Prepare staging build
        run: |
          # Make sure the staging site doesn't get indexed
          sed -i '/<head>/ a\    <meta name="robots" content="noindex">' _layouts/default.html
          # actions/jekyll-build-pages runs in a container as root
          # so files created by it are owned by root:root.
          # Pre-create the _site directory and use setgid to make sure files are created with the github runner gid
          mkdir _site
          chmod g+s _site
      - uses: actions/jekyll-build-pages@v1
      - uses: actions/upload-artifact@v2
        with:
          path: _site/
  validate:
    name: Validate HTML and CSS
    needs: [Build]
    runs-on: ubuntu-latest
    container:
      image: python:3.9-slim
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: artifact
      - run: |
          pwd
          ls -ahl
      - run: |
          mkdir -p /usr/share/man/man1/
          apt-get -qq update
          DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends -qq default-jre
          pip install html5validator==0.4.0 PyYAML==6.0
      - run: html5validator --also-check-css
  check-links:
    name: Check broken links
    needs: [Build]
    runs-on: ubuntu-latest
    container:
      image: ruby
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: artifact
      - run: |
          gem install html-proofer -v 3.19.3
          # Ignore 999 because LinkedIn is being annoying and returns 999 for any request done to
          # their site that isn't a browser :|
          htmlproofer --assume-extension --http_status_ignore="999"
  deploy:
    name: Deploy
    needs: [Build]
    runs-on: ubuntu-latest
    environment:
      name: staging
      url: https://staging.simonvanderveldt.nl
    steps:
      - name: Set GitHub Actions as commit author
        run: |
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com
      - name: Checkout staging repo
        uses: actions/checkout@v2
        with:
          repository: simonvanderveldt/staging.simonvanderveldt.nl
          ssh-key: ${{ secrets.STAGING_DEPLOY_SSH_KEY }}
      - uses: actions/download-artifact@v2
        with:
          name: artifact
      - name: Push to staging repo
        run: |
          ls -ahl
          # Site has already been built, so make sure it doesn't get built again
          touch .nojekyll
          # Set CNAME to staging subdomain
          echo "staging.simonvanderveldt.nl" > CNAME
          ls -ahl
          git add .
          git commit -m "Deploy commit $GITHUB_SHA"
          git push
